# Generated by Django 2.2.6 on 2020-12-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_testresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresults',
            name='subjects',
            field=models.CharField(max_length=900),
        ),
    ]
