# Generated by Django 2.2.6 on 2020-12-17 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20201217_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresults',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Createquestions'),
        ),
    ]
