# Generated by Django 2.2.6 on 2020-12-17 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20201217_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresults',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
