# Generated by Django 2.2.6 on 2020-12-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20201217_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresults',
            name='count',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
