# Generated by Django 2.2.6 on 2020-12-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='total',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
