# Generated by Django 2.2.6 on 2020-12-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_testresults_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
